
package services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EpisodeWebService", targetNamespace = "http://services/", wsdlLocation = "http://localhost:8080/My-IMDb-SOAP-WS/EpisodeWebService?wsdl")
public class EpisodeWebService_Service
    extends Service
{

    private final static URL EPISODEWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException EPISODEWEBSERVICE_EXCEPTION;
    private final static QName EPISODEWEBSERVICE_QNAME = new QName("http://services/", "EpisodeWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/My-IMDb-SOAP-WS/EpisodeWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EPISODEWEBSERVICE_WSDL_LOCATION = url;
        EPISODEWEBSERVICE_EXCEPTION = e;
    }

    public EpisodeWebService_Service() {
        super(__getWsdlLocation(), EPISODEWEBSERVICE_QNAME);
    }

    public EpisodeWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EPISODEWEBSERVICE_QNAME, features);
    }

    public EpisodeWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, EPISODEWEBSERVICE_QNAME);
    }

    public EpisodeWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EPISODEWEBSERVICE_QNAME, features);
    }

    public EpisodeWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EpisodeWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EpisodeWebService
     */
    @WebEndpoint(name = "EpisodeWebServicePort")
    public EpisodeWebService getEpisodeWebServicePort() {
        return super.getPort(new QName("http://services/", "EpisodeWebServicePort"), EpisodeWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EpisodeWebService
     */
    @WebEndpoint(name = "EpisodeWebServicePort")
    public EpisodeWebService getEpisodeWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services/", "EpisodeWebServicePort"), EpisodeWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EPISODEWEBSERVICE_EXCEPTION!= null) {
            throw EPISODEWEBSERVICE_EXCEPTION;
        }
        return EPISODEWEBSERVICE_WSDL_LOCATION;
    }

}
