
package services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GenreWebService", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GenreWebService {


    /**
     * 
     * @param genre
     * @return
     *     returns services.Genre
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addGenre", targetNamespace = "http://services/", className = "services.AddGenre")
    @ResponseWrapper(localName = "addGenreResponse", targetNamespace = "http://services/", className = "services.AddGenreResponse")
    @Action(input = "http://services/GenreWebService/addGenreRequest", output = "http://services/GenreWebService/addGenreResponse")
    public Genre addGenre(
        @WebParam(name = "genre", targetNamespace = "")
        Genre genre);

    /**
     * 
     * @return
     *     returns java.util.List<services.Genre>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listGenres", targetNamespace = "http://services/", className = "services.ListGenres")
    @ResponseWrapper(localName = "listGenresResponse", targetNamespace = "http://services/", className = "services.ListGenresResponse")
    @Action(input = "http://services/GenreWebService/listGenresRequest", output = "http://services/GenreWebService/listGenresResponse")
    public List<Genre> listGenres();

    /**
     * 
     * @param name
     * @return
     *     returns services.Genre
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateGenre", targetNamespace = "http://services/", className = "services.UpdateGenre")
    @ResponseWrapper(localName = "updateGenreResponse", targetNamespace = "http://services/", className = "services.UpdateGenreResponse")
    @Action(input = "http://services/GenreWebService/updateGenreRequest", output = "http://services/GenreWebService/updateGenreResponse")
    public Genre updateGenre(
        @WebParam(name = "name", targetNamespace = "")
        Genre name);

    /**
     * 
     * @param id
     * @return
     *     returns services.Genre
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteGenre", targetNamespace = "http://services/", className = "services.DeleteGenre")
    @ResponseWrapper(localName = "deleteGenreResponse", targetNamespace = "http://services/", className = "services.DeleteGenreResponse")
    @Action(input = "http://services/GenreWebService/deleteGenreRequest", output = "http://services/GenreWebService/deleteGenreResponse")
    public Genre deleteGenre(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param id
     * @return
     *     returns services.Genre
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findGenre", targetNamespace = "http://services/", className = "services.FindGenre")
    @ResponseWrapper(localName = "findGenreResponse", targetNamespace = "http://services/", className = "services.FindGenreResponse")
    @Action(input = "http://services/GenreWebService/findGenreRequest", output = "http://services/GenreWebService/findGenreResponse")
    public Genre findGenre(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

}
