
package services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GenreWebService", targetNamespace = "http://services/", wsdlLocation = "http://localhost:8080/My-IMDb-SOAP-WS/GenreWebService?wsdl")
public class GenreWebService_Service
    extends Service
{

    private final static URL GENREWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException GENREWEBSERVICE_EXCEPTION;
    private final static QName GENREWEBSERVICE_QNAME = new QName("http://services/", "GenreWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/My-IMDb-SOAP-WS/GenreWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GENREWEBSERVICE_WSDL_LOCATION = url;
        GENREWEBSERVICE_EXCEPTION = e;
    }

    public GenreWebService_Service() {
        super(__getWsdlLocation(), GENREWEBSERVICE_QNAME);
    }

    public GenreWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENREWEBSERVICE_QNAME, features);
    }

    public GenreWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, GENREWEBSERVICE_QNAME);
    }

    public GenreWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENREWEBSERVICE_QNAME, features);
    }

    public GenreWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenreWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GenreWebService
     */
    @WebEndpoint(name = "GenreWebServicePort")
    public GenreWebService getGenreWebServicePort() {
        return super.getPort(new QName("http://services/", "GenreWebServicePort"), GenreWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GenreWebService
     */
    @WebEndpoint(name = "GenreWebServicePort")
    public GenreWebService getGenreWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services/", "GenreWebServicePort"), GenreWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GENREWEBSERVICE_EXCEPTION!= null) {
            throw GENREWEBSERVICE_EXCEPTION;
        }
        return GENREWEBSERVICE_WSDL_LOCATION;
    }

}
