
package services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SeasonWebService", targetNamespace = "http://services/", wsdlLocation = "http://localhost:8080/My-IMDb-SOAP-WS/SeasonWebService?wsdl")
public class SeasonWebService_Service
    extends Service
{

    private final static URL SEASONWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SEASONWEBSERVICE_EXCEPTION;
    private final static QName SEASONWEBSERVICE_QNAME = new QName("http://services/", "SeasonWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/My-IMDb-SOAP-WS/SeasonWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEASONWEBSERVICE_WSDL_LOCATION = url;
        SEASONWEBSERVICE_EXCEPTION = e;
    }

    public SeasonWebService_Service() {
        super(__getWsdlLocation(), SEASONWEBSERVICE_QNAME);
    }

    public SeasonWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEASONWEBSERVICE_QNAME, features);
    }

    public SeasonWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SEASONWEBSERVICE_QNAME);
    }

    public SeasonWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEASONWEBSERVICE_QNAME, features);
    }

    public SeasonWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SeasonWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SeasonWebService
     */
    @WebEndpoint(name = "SeasonWebServicePort")
    public SeasonWebService getSeasonWebServicePort() {
        return super.getPort(new QName("http://services/", "SeasonWebServicePort"), SeasonWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SeasonWebService
     */
    @WebEndpoint(name = "SeasonWebServicePort")
    public SeasonWebService getSeasonWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services/", "SeasonWebServicePort"), SeasonWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEASONWEBSERVICE_EXCEPTION!= null) {
            throw SEASONWEBSERVICE_EXCEPTION;
        }
        return SEASONWEBSERVICE_WSDL_LOCATION;
    }

}
